export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  LOADER = 'LOADER',
  STORE = 'STORE',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  VIEWER = 'VIEWER',
  TEAM_LEAD = 'TEAM_LEAD',
}
